# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e34be6f-a042-433e-bcfc-9df254a571c3";
      fsType = "ext4";
    };

  nix.settings.max-jobs = lib.mkDefault 3;
}
