#!/usr/bin/env bash
hyprctl activewindow -j | jaq -c .
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
    stdbuf -o0 grep -ose '^activewindow>>' | while read -r line; do
  hyprctl activewindow -j | jaq -c .
done
