#!/usr/bin/env bash

volume() {
  echo '{"value":'$(pamixer --get-volume)',"muted":"'$(pamixer --get-mute)'"}'
}

volume
pw-mon -oa | stdbuf -o0 grep -os "changed:" | while read -r line; do
  volume
done
